<a href="https://colab.research.google.com/github/ArnavCodes1000101/python_assignment_IIT/blob/OTHERS(ITM-OR-PERSONAL-PROJECT)/Shopping_List_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
products = { "Milk": {"price in rupees": 60, "quantity": 10},
"Bread": {"price in rupees": 40, "quantity": 15},
"Eggs": {"price in rupees": 120, "quantity": 20},
"Rice": {"price in rupees": 80, "quantity": 25},
"Biscuits": {"price in rupees": 30, "quantity": 30} }

import pandas as pd
df = pd.DataFrame(products).T
print("Available Products:")
display(df)

cart = []
total = 0

while True:
    my_product = input("Enter the product you want to buy (q to quit): ")

    if my_product == 'q':
        break

    if my_product in products:
        try:
            quantity = int(input(f"Enter quantity for {my_product}: "))

            available_stock = products[my_product]["quantity"]
            if quantity <= available_stock:
                unit_price = products[my_product]['price in rupees']
                item_price = quantity * unit_price

                cart.append({
                    'product': my_product,
                    'quantity': quantity,
                    'unit_price': unit_price,
                    'total_price': item_price })

                total += item_price

                products[my_product]['quantity'] -= quantity
                print(f"{quantity} x {my_product} added to cart.")
            else:
                print(f"Insufficient stock for {my_product}. Available: {available_stock}.enter a lower quantity.")

        except ValueError:
            print("Invalid quantity. Please enter a valid number.")
    else:
        print(f"Product '{my_product}' not found. choose from  available products.")

print(" Your Shopping Cart")
for item in cart:
        print(f"- {item['product']} (x{item['quantity']}): ₹{item['unit_price']} each, Total: ₹{item['total_price']}")



        print(f"Grand Total of your purchase: ₹{total}")

display(pd.DataFrame(products).T)

Available Products:

          price in rupees  quantity
Milk                   60        10
Bread                  40        15
Eggs                  120        20
Rice                   80        25
Biscuits               30        30

Enter the product you want to buy (q to quit): Eggs
Enter quantity for Eggs: 19
19 x Eggs added to cart.
Enter the product you want to buy (q to quit): Riced
Product 'Riced' not found. choose from  available products.
Enter the product you want to buy (q to quit): Rice
Enter quantity for Rice: 24
24 x Rice added to cart.
Enter the product you want to buy (q to quit): q
 Your Shopping Cart
- Eggs (x19): ₹120 each, Total: ₹2280
Grand Total of your purchase: ₹4200
- Rice (x24): ₹80 each, Total: ₹1920
Grand Total of your purchase: ₹4200

          price in rupees  quantity
Milk                   60        10
Bread                  40        15
Eggs                  120         1
Rice                   80         1
Biscuits               30        30